#!/usr/bin/env bash
# IMM 5710 fr (Demande pour proroger/modifier les conditions de séjour — travailleur)
# Full intake enrichment, reduction-aware. Idempotent: every mutation upserts.
#
# Targets the deployment configured in .env.local (dev). Runs in order:
#   1. seed 53 canonical gap questions the form needs (must exist before step 3)
#   2. set the 96-question immQuestions mapping + 5 required documents
#   3. wire 26 dependsOn rules (conditional visibility — Lever C)
#
# Generated by the intake pipeline (see README.md). Data lives in ./data/*.json
# so it can be reviewed/diffed; this script just applies it.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$SCRIPT_DIR/data"
CONVEX_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

run() { (cd "$CONVEX_DIR" && npx convex run "$1" "$(cat "$2")"); }

echo "[1/3] seeding 53 canonical gap questions…"
run questions:seedCanonicalQuestions      "$DATA_DIR/imm5710fr-gaps.json"          >/dev/null
echo "[2/3] setting immQuestions (96 intake questions + 5 required documents)…"
run legalDocuments:setImmQuestions         "$DATA_DIR/imm5710fr-immquestions.json"  >/dev/null
echo "[3/3] wiring 26 dependsOn rules…"
run questions:setQuestionDependsOnBatch    "$DATA_DIR/imm5710fr-dependson.json"     >/dev/null
echo "[done] IMM 5710 fr enriched. Verify with getIntakeForClient stats."
